#:schema https://raw.githubusercontent.com/phothinmg/peisar/refs/heads/main/schema/peisar-ssg.json

[site]
title = "My Site"
description = ""

[directories]
contents_dir = "contents"
public_dir = "public"
out_dir = ".peisar"
