/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Parses one Markdown document and exposes its AST, HTML, and front matter
 * to JavaScript.
 *
 * Construct this class with the Markdown source and an optional
 * [`PeisarOptions`] object. Properties are computed from the source document;
 * accessing `ast`, `html`, or `astJson` also applies registered visitors.
 */
export declare class Peisar {
  /**
   * Creates a parser for `rawMd`.
   *
   * When `options` is omitted, GFM and Kramdown parsing are enabled and
   * `html` returns a complete HTML document.
   */
  constructor(rawMd: string, options?: PeisarOptions | undefined | null)
  /**
   * Gets the parsed Markdown document as a JavaScript AST object.
   *
   * Registered visitors run before the AST is returned. The returned value
   * is a clone, so reading this property does not consume the parser state.
   */
  get ast(): Document
  /**
   * Registers a JavaScript AST visitor.
   *
   * The visitor can provide `visitBlock` and/or `visitInline` callbacks.
   * Each callback receives a one-item node tuple and may return a control object that
   * changes the node or determines whether its children are visited.
   */
  useVisitor(visitor: Visitor): void
  /**
   * Registers a JavaScript custom parser hook.
   *
   * The parser can provide `parseBlock` and/or `parseInline` callbacks.
   * `parseBlock` receives `{ line, lineIndex, lines }` and returns
   * `{ block, consumed }`; `parseInline` receives `{ rest, index }` and
   * returns `{ inline, consumed }`.  Return `undefined` (or omit the
   * node) to decline a position.
   *
   * Hooks run before the built-in parsers, in registration order.  Since
   * the document is parsed at construction, registering a parser hook
   * re-parses the original Markdown so hook syntax is recognized.
   */
  useParser(parser: Parser): void
  /**
   * Renders the parsed Markdown as HTML using the configured render options.
   *
   * Registered visitors run before rendering.
   */
  get html(): string
  /** Gets the deserialized YAML front matter, or `null` when none exists. */
  get frontmatter(): any | null
  /**
   * Gets the parsed Markdown AST serialized as JSON.
   *
   * Registered visitors run before serialization.
   */
  get astJson(): string
}

/**
 * In-memory cache of markdown files under a given directory.
 * The cache maps absolute PathBuf -> raw file contents.
 */
export declare class PeisarCache {
  /**
   * Construct a new PeisarCache using the default discovery behavior.
   *
   * This is equivalent to calling `with_config(entry_dir, None)` and will
   * use the "public" directory at project root when present.
   *
   * JS: `new PeisarCache(entryDir, assetsDir?)` — both plain strings.
   */
  constructor(entryDir: string, assetsDir?: string | undefined | null)
  /**
   * JS: same as the constructor, for callers that prefer a factory shape.
   * Kept non-generic so NAPI can export it.
   */
  static withConfigJs(entryDir: string, assetsDir?: string | undefined | null): PeisarCache
  /**
   * Start watching the entry_dir recursively. The watcher will update the
   * in-memory cache on create/modify/remove events for markdown files and
   * assets, and persist updates to disk.
   *
   * The returned Result is only for watcher setup errors; runtime errors are
   * printed to stderr by the watch callback.
   *
   * JS: `cache.startWatching()` — errors surface as JS exceptions.
   */
  startWatchingJs(): void
  /**
   * ----------------------------------------------------------------
   * JavaScript (NAPI) surface
   * ----------------------------------------------------------------
   * All JS methods take/return plain strings because `&Path`/`PathBuf`
   * do not cross the NAPI boundary.
   * JS: `cache.getText(absPath)` — cached text of a file, or null.
   */
  getText(absPath: string): string | null
  /** JS: `cache.getBinary(absPath)` — cached bytes of a binary asset, or null. */
  getBinary(absPath: string): Array<number> | null
  /** JS: `cache.listFiles()` — absolute paths of everything cached. */
  listFiles(): Array<string>
  /** JS: `cache.markdownFiles()` — absolute paths of cached markdown files. */
  markdownFiles(): Array<string>
  /** JS: `cache.assetFiles()` — absolute paths of cached non-markdown files. */
  assetFiles(): Array<string>
  /**
   * JS: `cache.onChange(cb)` — invoke `cb(event)` on every file change the
   * watcher detects while watching is active. Returns a subscription id
   * that can be passed to `offChange(id)`.
   *
   * The callback is wrapped in a `ThreadsafeFunction` because notify
   * events fire on the watcher thread, not the JS main thread.
   */
  onChange(callback: (event: CacheChangeEvent) => void): number
  /** JS: `cache.offChange(id)` — remove a previously registered callback. */
  offChange(id: number): void
  /**
   * JS: `cache.dispose()` — stop the watcher and drop JS change callbacks.
   * Safe to call more than once.
   */
  dispose(): void
}

/**
 * Options that control how Markdown is parsed.
 *
 * # Defaults
 *
 * Both GFM and Kramdown extensions are enabled by default.  To parse
 * strict CommonMark only:
 */
export interface AstOptions {
  /**
   * Enable GitHub Flavored Markdown (tables, strikethrough, task lists,
   * autolinks).  Default: `true`.
   */
  gfm: boolean
  /**
   * Enable Kramdown-style block attributes (`{:#id .class key="val"}`).
   * Default: `true`.
   */
  kramdown: boolean
  /** Optional file name to attach to the parsed [`Document`](crate::Document). */
  fileName?: string
}

/** Parsed Kramdown block attributes (`{:#id .class key="val"}`). */
export interface Attributes {
  /** HTML `id` attribute. */
  id?: string
  /** CSS class list. */
  classes?: Array<string>
  /** Arbitrary key/value attributes. */
  attributes?: Array<[string, string]>
}

/** Block-level nodes. */
export type Block =
  | { type: 'Heading'; /** Heading level (1–6). */
    level: number; /** Inline content of the heading. */
    children: Array<Inline>; /** Source span. */
    pos: Span; /** Optional Kramdown attributes. */
  attrs?: Attributes }
  | { type: 'Paragraph'; /** Inline content of the paragraph. */
    children: Array<Inline>; /** Source span. */
    pos: Span; /** Optional Kramdown attributes. */
  attrs?: Attributes }
  | { type: 'CodeBlock'; /** Language hint from the info string (e.g. `rust` from ` ```rust `). */
    lang?: string; /** The raw code content. */
    code: string; /** Source span. */
    pos: Span; /** Optional Kramdown attributes. */
  attrs?: Attributes }
  | { type: 'BlockQuote'; /** Nested block content inside the quote. */
    children: Array<Block>; /** Source span. */
    pos: Span; /** Optional Kramdown attributes. */
  attrs?: Attributes }
  | { type: 'List'; /** `true` for ordered lists, `false` for unordered. */
    ordered: boolean; /** The list items. */
    items: Array<ListItem>; /** Source span. */
    pos: Span; /** Optional Kramdown attributes. */
  attrs?: Attributes }
  | { type: 'ThematicBreak'; /** Source span. */
  pos: Span }
  | { type: 'HtmlBlock'; /** The raw HTML content. */
    html: string; /** Source span. */
    pos: Span; /** Optional Kramdown attributes. */
  attrs?: Attributes }
  | { type: 'Table'; /** The table structure (header, rows, alignments). */
    table: Table; /** Source span. */
    pos: Span; /** Optional Kramdown attributes. */
  attrs?: Attributes }
  | { type: 'LinkReferenceDefinition'; /** Normalised label (lowercased, trimmed). */
    label: string; /** The destination URL. */
    url: string; /** Optional link title. */
    title?: string; /** Source span. */
  pos: Span }
  | { type: 'Comment'; /** The comment text (markers stripped). */
    value: string; /** Source span. */
  pos: Span }

/**
 * Synchronous block-visitor callback. Receives a `Block`, returns
 * `VisitControlJs` (or `undefined` for no changes).
 */
export type BlockCallback = (arg: [Block]) => VisitControlJs | null

/**
 * Synchronous block parser hook. Receives a [`BlockParseContext`], returns
 * a [`BlockParseResultJs`] (or `undefined` to decline).
 */
export type BlockParseCallback = (arg: [BlockParseContext]) => BlockParseResultJs | null

/**
 * Context passed to block parser hooks.
 *
 * On the JavaScript side the fields are exposed as `line`, `lineIndex`,
 * and `lines`.
 */
export interface BlockParseContext {
  /** The current (unmodified) source line. */
  line: string
  /** 0-based index of the current line in the (sub-)document. */
  lineIndex: number
  /** Remaining lines starting at the current line (`lines[0]` is `line`). */
  lines: Array<string>
}

/**
 * Result returned from the JS `parseBlock` callback.
 *
 * All fields are optional; omitting `block` (or returning `undefined`)
 * declines the position so the next hook / built-in parser handles it.
 */
export interface BlockParseResultJs {
  /** The parsed block node. */
  block?: Block
  /** Number of source lines consumed (must be at least `1`). */
  consumed?: number
}

/** A file-change event delivered to JavaScript `onChange` callbacks. */
export interface CacheChangeEvent {
  /** Absolute path of the changed file. */
  path: string
  /** `"create"`, `"modify"`, or `"remove"`. */
  kind: string
  /** `true` when the file is under the markdown entry directory. */
  isMarkdown: boolean
}

export type CachedContent =
  | { type: 'Text'; field0: string }
  | { type: 'Binary'; field0: Array<number> }

/**
 * A Markdown document — the root of the AST.
 *
 * Contains the top-level block children and all link reference definitions
 * collected from the source text.
 */
export interface Document {
  /** Always `"root"`. */
  nodeType: string
  /** Optional source file name. */
  fileName?: string
  /** Span of the whole document in the source text. */
  pos: Span
  /** Top-level block children. */
  children: Array<Block>
  /** All link reference definitions collected from the document. */
  linkReferences: Array<LinkReferenceDefinition>
}

/** Emphasis strength. */
export declare const enum EmphasisLevel {
  /** `*italic*` / `_italic_` */
  Italic = 0,
  /** `**bold**` / `__bold__` */
  Bold = 1,
}

/** Inline-level nodes. */
export type Inline =
  | { type: 'Text'; /** The text value. */
    value: string; /** Source span. */
  pos: Span }
  | { type: 'Emphasis'; /** Emphasis level (italic or bold). */
    level: EmphasisLevel; /** Nested inline content. */
    children: Array<Inline>; /** Source span. */
  pos: Span }
  | { type: 'Code'; /** The code text. */
    code: string; /** Source span. */
  pos: Span }
  | { type: 'HtmlInline'; /** The raw HTML string. */
    html: string; /** Source span. */
  pos: Span }
  | { type: 'Strikethrough'; /** Nested inline content. */
    children: Array<Inline>; /** Source span. */
  pos: Span }
  | { type: 'HardBreak'; /** Source span. */
  pos: Span }
  | { type: 'SoftBreak'; /** Source span. */
  pos: Span }
  | { type: 'Image'; /** Alternative text. */
    alt: string; /** Image URL. */
    url: string; /** Optional title. */
    title?: string; /** Source span. */
  pos: Span }
  | { type: 'Link'; /** Link text (inline children). */
    text: Array<Inline>; /** Destination URL. */
    url: string; /** Optional link title. */
    title?: string; /** `true` if this is a GFM autolink (bare URL). */
    autolink: boolean; /** Source span. */
  pos: Span }
  | { type: 'LinkReference'; /** Link text (inline children). */
    text: Array<Inline>; /** Normalised label used to look up the reference. */
    label: string; /** Resolved destination URL. */
    url: string; /** Optional resolved title. */
    title?: string; /** Source span. */
  pos: Span }

/**
 * Synchronous inline-visitor callback. Receives an `Inline`, returns
 * `InlineVisitControlJs` (or `undefined` for no changes).
 */
export type InlineCallback = (arg: [Inline]) => InlineVisitControlJs | null

/**
 * Synchronous inline parser hook. Receives an [`InlineParseContext`],
 * returns an [`InlineParseResultJs`] (or `undefined` to decline).
 */
export type InlineParseCallback = (arg: [InlineParseContext]) => InlineParseResultJs | null

/**
 * Context passed to inline parser hooks.
 *
 * On the JavaScript side the fields are exposed as `rest` and `index`.
 */
export interface InlineParseContext {
  /** Remaining inline text starting at the current character position. */
  rest: string
  /** 0-based character index of the current position in the inline text. */
  index: number
}

/**
 * Result returned from the JS `parseInline` callback.
 *
 * All fields are optional; omitting `inline` (or returning `undefined`)
 * declines the position so the next hook / built-in parser handles it.
 */
export interface InlineParseResultJs {
  /** The parsed inline node. */
  inline?: Inline
  /** Number of characters consumed (`0` or missing declines). */
  consumed?: number
}

/**
 * JS-facing mirror of [`InlineVisitControl`].
 *
 * Returned from the JS `visitInline` callback.  All fields are optional;
 * omitting a field means "no change" for that operation.
 */
export interface InlineVisitControlJs {
  /** Nodes to insert before the current node. */
  insertBefore?: Array<Inline>
  /** Nodes to insert after the current node. */
  insertAfter?: Array<Inline>
  /** Replace the current node with these nodes. */
  replaceWith?: Array<Inline>
  /** Remove the current node entirely. */
  remove?: boolean
  /** Whether to recurse into this node's children. */
  recurse?: boolean
}

/** A link reference definition collected at the document level. */
export interface LinkReferenceDefinition {
  /** Normalised label (lowercased, trimmed). */
  label: string
  /** The destination URL. */
  url: string
  /** Optional link title. */
  title?: string
  /** Source span. */
  pos: Span
}

/** A single list item (an `<li>`). Contains nested block content. */
export interface ListItem {
  /** Nested block content of the item. */
  children: Array<Block>
  /** GFM task-list state: `None` = not a task, `Some` = checked / unchecked. */
  task?: TaskState
  /** Span of the item in the *sub-document* of its enclosing list. */
  pos: Span
}

/**
 * JavaScript object shape for a parser hook pair.
 *
 * ```js
 * const myParser = {
 *   parseBlock(ctx) {
 *     if (!ctx.line.startsWith(':::')) return;         // decline
 *     const name = ctx.line.slice(3).trim();
 *     return {
 *       block: { type: 'HtmlBlock', html: `<div data-name="${name}"></div>`, pos: { start: {}, end: {} } },
 *       consumed: 1,
 *     };
 *   },
 *   parseInline(ctx) {
 *     if (!ctx.rest.startsWith('@@')) return;          // decline
 *     const end = ctx.rest.indexOf(' ', 2);
 *     const name = end === -1 ? ctx.rest.slice(2) : ctx.rest.slice(2, end);
 *     return {
 *       inline: { type: 'HtmlInline', html: `<span data-name="${name}"></span>`, pos: { start: {}, end: {} } },
 *       consumed: name.length + 2,
 *     };
 *   },
 * };
 * document.useParser(myParser);
 * ```
 *
 * Either property may be omitted / `null` to skip that phase.
 */
export interface Parser {
  /** Optional JS block parser hook (JS: `parseBlock`). */
  parseBlock?: BlockParseCallback
  /** Optional JS inline parser hook (JS: `parseInline`). */
  parseInline?: InlineParseCallback
}

/** The Markdown body and YAML metadata parsed from a front-matter document. */
export interface ParseResult {
  /** Markdown source after the leading YAML front matter is removed. */
  pureMarkdownContent: string
  /** Deserialized YAML front matter, or `null` when no front matter exists. */
  yamlData?: Record<string, any>
}

/**
 * JavaScript options for Markdown parsing and HTML rendering.
 *
 * Every property is optional. Omitted parsing options enable GFM and
 * Kramdown; omitted rendering options produce a complete HTML document with
 * charset and viewport metadata.
 */
export interface PeisarOptions {
  /**
   * Enable GitHub Flavored Markdown (tables, strikethrough, task lists,
   * autolinks).  Default: `true`.
   */
  gfm?: boolean
  /**
   * Enable Kramdown-style block attributes (`{:#id .class key="val"}`).
   * Default: `true`.
   */
  kramdown?: boolean
  /** Optional file name to attach to the parsed [`Document`](crate::Document). */
  fileName?: string
  /**
   * If `true`, emit only the body content (no `<!DOCTYPE>`, `<html>`,
   * `<head>`, or `<body>` wrapper).  If `false`, emit a full HTML
   * document.  Default: `true` (fragment).
   */
  fragment?: boolean
  /**
   * Include a `<meta charset="utf-8">` in the head (only relevant when
   * `fragment` is `false`).  Default: `true`.
   */
  charset?: boolean
  /**
   * Include a `<meta name="viewport" content="width=device-width,
   * initial-scale=1.0">` in the head (only relevant when `fragment` is
   * `false`).  Default: `true`.
   */
  viewport?: boolean
  /**
   * Optional `<title>` for the HTML head (only relevant when
   * `fragment` is `false`).  Default: `None`.
   */
  title?: string
  /**
   * Optional additional CSS classes to add to `<body>` (only relevant
   * when `fragment` is `false`).  Default: `None`.
   */
  bodyClass?: string
  /**
   * Optional inline CSS to inject in a `<style>` tag in the head.
   * Default: `None`.
   */
  style?: string
}

/**
 * N-API entry point: loads the site configuration from `Peisar.toml` in the
 * current working directory.
 *
 * Exposed to JavaScript as `peisarSsgConfig()`. On success it returns a
 * fully-resolved [`PeisarSSGConfig`] object. On failure it prints the error
 * message to stderr and terminates the host process with exit code `1` — a
 * missing file, an invalid file and an empty `[site] title` are all fatal.
 *
 * Rust consumers should prefer [`load_config`], which reports errors as
 * values instead of exiting.
 */
export declare function peisarSsgConfig(): PeisarSsgConfig

/**
 * Fully-resolved site configuration.
 *
 * Every optional value from `Peisar.toml` has been replaced by either the
 * value from the file or its documented default, so consumers never have to
 * handle `Option`s.
 */
export interface PeisarSsgConfig {
  /** Site metadata. */
  site: PeisarSsgSite
  /** Directory configuration. */
  directories: PeisarSsgDirectories
  /** Development-server configuration. */
  devServer: PeisarSsgDevServer
}

/**
 * Development-server settings, resolved from the optional `[devServer]` table
 * of `Peisar.toml`.
 */
export interface PeisarSsgDevServer {
  /** TCP port the dev server listens on. Default: `3838`. */
  port: number
  /** Address the dev server binds to. Default: `"127.0.0.1"`. */
  host: string
}

/**
 * Directory configuration, resolved from the optional `[directories]` table
 * of `Peisar.toml`.
 *
 * In JavaScript the fields appear in camelCase: `rootDir`, `contentsDir`,
 * `publicDir`, `themeDir` and `outDir`.
 */
export interface PeisarSsgDirectories {
  /** Project root directory. Default: `"."`. */
  rootDir: string
  /** Directory containing the markdown contents. Default: `"contents"`. */
  contentsDir: string
  /**
   * Directory with static assets copied verbatim to the output.
   * Default: `"public"`.
   */
  publicDir: string
  /** Directory containing the theme. Default: `"themes"`. */
  themeDir: string
  /** Build output directory. Default: `".peisar"`. */
  outDir: string
}

/**
 * Site metadata, resolved from the `[site]` table of `Peisar.toml`.
 *
 * In JavaScript the fields keep their names: `title`, `description`, `author`.
 */
export interface PeisarSsgSite {
  /** Site title (required and non-empty). */
  title: string
  /** Site description, if the config file sets one. */
  description?: string
  /** Site author, if the config file sets one. */
  author?: string
}

/** A zero-based point in the source text. */
export interface Position {
  /** Line number, 0-based. */
  line: number
  /** Column number, 0-based (in characters). */
  column: number
  /** Byte offset from the start of the input. */
  offset: number
}

/** Options that control how the AST is rendered to HTML. */
export interface RenderOptions {
  /**
   * If `true`, emit only the body content (no `<!DOCTYPE>`, `<html>`,
   * `<head>`, or `<body>` wrapper).  If `false`, emit a full HTML
   * document.  Default: `true` (fragment).
   */
  fragment: boolean
  /**
   * Include a `<meta charset="utf-8">` in the head (only relevant when
   * `fragment` is `false`).  Default: `true`.
   */
  charset: boolean
  /**
   * Include a `<meta name="viewport" content="width=device-width,
   * initial-scale=1.0">` in the head (only relevant when `fragment` is
   * `false`).  Default: `true`.
   */
  viewport: boolean
  /**
   * Optional `<title>` for the HTML head (only relevant when
   * `fragment` is `false`).  Default: `None`.
   */
  title?: string
  /**
   * Optional additional CSS classes to add to `<body>` (only relevant
   * when `fragment` is `false`).  Default: `None`.
   */
  bodyClass?: string
  /**
   * Optional inline CSS to inject in a `<style>` tag in the head.
   * Default: `None`.
   */
  style?: string
}

/**
 * A half-open span `[start, end)` covering a node's source text.
 *
 * `start` is inclusive and `end` is exclusive; both positions point into the
 * original source string.
 */
export interface Span {
  /** The start position (inclusive). */
  start: Position
  /** The end position (exclusive). */
  end: Position
}

/** A GFM table. */
export interface Table {
  /** The header row. */
  header: TableRow
  /** Body rows. */
  rows: Array<TableRow>
  /** Column alignment specifications (one per column). */
  alignments: Array<TableCellAlignment>
}

/** A single table cell. */
export interface TableCell {
  /** Inline content of the cell. */
  children: Array<Inline>
}

/** Column alignment for table cells. */
export declare const enum TableCellAlignment {
  /** `:---` or `---` — default (left) */
  Default = 0,
  /** `:---` */
  Left = 1,
  /** `:---:` */
  Center = 2,
  /** `---:` */
  Right = 3,
}

/** A single table row (header or body). */
export interface TableRow {
  /** The cells in this row. */
  cells: Array<TableCell>
}

/** GFM task-list checkbox state. */
export declare const enum TaskState {
  /** `[ ]` — unchecked */
  Unchecked = 0,
  /** `[x]` / `[X]` — checked */
  Checked = 1,
}

/**
 * JS-facing mirror of [`VisitControl`].
 *
 * Returned from the JS `visitBlock` callback.  All fields are optional;
 * omitting a field means "no change" for that operation.
 */
export interface VisitControlJs {
  /** Nodes to insert before the current node. */
  insertBefore?: Array<Block>
  /** Nodes to insert after the current node. */
  insertAfter?: Array<Block>
  /** Replace the current node with these nodes. */
  replaceWith?: Array<Block>
  /** Remove the current node entirely. */
  remove?: boolean
  /** Whether to recurse into this node's children. */
  recurse?: boolean
}

/**
 * JavaScript object shape for a visitor callback pair.
 *
 * On the JS side it is a plain object with two optional
 * function properties:
 *
 * ```js
 * const myPlugin = {
 *   visitBlock(block)  { return { recurse: true }; },
 *   visitInline(inline) { return {}; },
 * };
 * ast.addVisitor(myPlugin);
 * ```
 *
 * Either property may be omitted / `null` to skip that node kind.
 */
export interface Visitor {
  /** Optional JS callback for block nodes (JS: `visitBlock`). */
  visitBlock?: BlockCallback
  /** Optional JS callback for inline nodes (JS: `visitInline`). */
  visitInline?: InlineCallback
}
